export enum ROUTES {
  LOGIN = 'login',
  REGISTER = 'register',
  MAIN_PAGE = 'main-page',
  USER_PROFILE = 'profile',
  SURVEYS = 'surveys',
  SURVEY_DETAIL = 'surveys/:id',
  SURVEY_TAKE = 'surveys/:id/take',
  ABOUT = 'about',
  REPORTS = 'reports',
  PREORDER = 'preorder',
  STATISTICS = 'statistics',
  ADMIN_USERS = 'admin/users',
  ADMIN_SURVEYS = 'admin/surveys',
  USER_SURVEYS = 'user/surveys',
  CONTACT = 'contact',
}
