import { StatStatus } from '../../shared/models/enums';

export interface SurveyData {
  id: string;
  title: string;
  coverImage: string;
  category: string;
  status: StatStatus;
  description: string;
  about: string;
  questionsCount: number;
  estimatedTime: string;
  activeUntil: string;
  author: string;
  authorAvatar: string;
  participants: number;
}

export const SURVEY_DETAIL_MOCK: SurveyData[] = [
  {
    id: 'survey:019de9f1-0001-7001-b001-c3d4e5f60101',
    title: 'Do We Rely Too Much on Technology?',
    coverImage: '/assets/images/banner/card1.png',
    category: 'society',
    status: StatStatus.Active,
    description: 'Explore how dependent modern society has become on digital tools — and whether that dependence is leading us somewhere we actually want to go.',
    about: 'This survey explores the relationship between modern society and digital technology — from daily screen time to the deeper question of whether we\'re heading in a direction we actually chose.',
    questionsCount: 4,
    estimatedTime: '5 min',
    activeUntil: 'Anonymous survey',
    author: 'Alex Monroe',
    authorAvatar: '',
    participants: 2847,
  },
  {
    id: 'survey:019de9f2-0001-7001-b002-c3d4e5f60102',
    title: 'Is Space Exploration Worth the Cost?',
    coverImage: '/assets/images/banner/card2.png',
    category: 'science',
    status: StatStatus.Active,
    description: 'Humanity spends billions reaching for the stars. Share your perspective on whether that investment makes sense — or where it should go instead.',
    about: 'From Moon landings to Mars missions, space exploration demands enormous resources. This survey gathers perspectives on whether the scientific, cultural and economic returns justify the investment.',
    questionsCount: 4,
    estimatedTime: '4 min',
    activeUntil: 'Anonymous survey',
    author: 'Lena Oris',
    authorAvatar: '',
    participants: 1956,
  },
  {
    id: 'survey:019de9f3-0001-7001-b003-c3d4e5f60103',
    title: 'What Shapes Who We Are?',
    coverImage: '/assets/images/banner/card3.png',
    category: 'psychology',
    status: StatStatus.Active,
    description: "Nature, environment, or chance — what do you believe has the greatest influence on a person's identity? No wrong answers.",
    about: "Identity is one of the most debated questions in psychology. This survey explores how people understand the forces that shaped them — genetics, upbringing, culture, or something else entirely.",
    questionsCount: 4,
    estimatedTime: '7 min',
    activeUntil: 'Anonymous survey',
    author: 'Mark Vega',
    authorAvatar: '',
    participants: 2103,
  },
  {
    id: 'survey:019de9f4-0001-7001-b004-c3d4e5f60104',
    title: 'Myths & Facts: The Human Brain',
    coverImage: '/assets/images/banner/card4.png',
    category: 'science',
    status: StatStatus.Active,
    description: 'We only use 10% of our brains. Or do we? Separate common misconceptions from science in this quick knowledge test.',
    about: "The brain is surrounded by myths that sound convincing but don't hold up. This test challenges popular beliefs about memory, intelligence, and neurological function with evidence-based questions.",
    questionsCount: 4,
    estimatedTime: '8 min',
    activeUntil: 'May 1, 2027',
    author: 'Sofia Lane',
    authorAvatar: '',
    participants: 1648,
  },
  {
    id: 'survey:019de95c-3401-7001-a1b2-c3d4e5f60001',
    title: 'How Do You Handle Stress?',
    coverImage: '/assets/images/banner/card1.png',
    category: 'psychology',
    status: StatStatus.Active,
    description: 'Stress is part of modern life — but how we handle it varies widely. Share your coping strategies and what genuinely works for you.',
    about: 'Everyone experiences stress differently. This survey maps out real coping strategies across our community — from exercise and sleep to social support and mindfulness.',
    questionsCount: 3,
    estimatedTime: '5 min',
    activeUntil: 'Anonymous survey',
    author: 'Ivan Petrov',
    authorAvatar: '',
    participants: 1284,
  },
  {
    id: 'survey:019de96a-0001-7000-8000-c3d4e5f60001',
    title: 'How Do You Learn Best?',
    coverImage: '/assets/images/banner/card2.png',
    category: 'psychology',
    status: StatStatus.Active,
    description: 'Everyone absorbs information differently. Help us understand what makes learning click — your preferred formats, timing, and goals.',
    about: 'Learning styles, pacing and motivation differ from person to person. This survey explores the habits and preferences that help people retain information — and where traditional education formats fall short.',
    questionsCount: 5,
    estimatedTime: '10 min',
    activeUntil: 'Anonymous survey',
    author: 'Dana Kol',
    authorAvatar: '',
    participants: 1847,
  },
  {
    id: 'survey:019ded05-5fbc-7e45-919f-ea20c34a34ac',
    title: 'Sleep & Your Daily Energy',
    coverImage: '/assets/images/banner/card3.png',
    category: 'psychology',
    status: StatStatus.Active,
    description: 'Sleep shapes everything — mood, focus, productivity. Tell us about your sleep habits and what you wish you could change.',
    about: 'Sleep is one of the most underestimated factors in daily performance. This survey collects honest insights about real sleep patterns, their impact on energy levels, and the changes people wish they could make.',
    questionsCount: 4,
    estimatedTime: '7 min',
    activeUntil: 'Anonymous survey',
    author: 'Alex Monroe',
    authorAvatar: '',
    participants: 2390,
  },
  {
    id: 'survey:019ded10-b3a3-7bc1-a0bc-7a31ff091616',
    title: 'The Human Body: Fact or Fiction?',
    coverImage: '/assets/images/banner/card4.png',
    category: 'science',
    status: StatStatus.Active,
    description: 'How well do you know your own body? Test your knowledge of human biology with these quick questions.',
    about: 'This test covers biology basics about the human body — from digestion and the nervous system to common misconceptions about how our bodies actually work.',
    questionsCount: 3,
    estimatedTime: '10 min',
    activeUntil: 'May 1, 2027',
    author: 'Mark Vega',
    authorAvatar: '',
    participants: 1523,
  },
  {
    id: 'survey:019ded26-cabe-71af-bc58-ac1b804617c0',
    title: 'Great Thinkers: Know Your Philosophy?',
    coverImage: '/assets/images/banner/card1.png',
    category: 'philosophy',
    status: StatStatus.Active,
    description: "From Socrates to Nietzsche — how much do you know about the world's most influential philosophical ideas?",
    about: "Philosophy shaped how we think about justice, reality, consciousness and ethics. This test challenges your knowledge of the ideas and thinkers who changed the course of human thought.",
    questionsCount: 3,
    estimatedTime: '15 min',
    activeUntil: 'May 1, 2027',
    author: 'Ivan Petrov',
    authorAvatar: '',
    participants: 3126,
  },
  {
    id: 'survey:019ded3a-dead-beef-8888-c3d4e5f60001',
    title: 'Digital Wellbeing Check — Winter 2026',
    coverImage: '/assets/images/banner/card2.png',
    category: 'wellbeing',
    status: StatStatus.Passed,
    description: "A snapshot of how digital habits affected our community's wellbeing at the start of 2026. Now closed.",
    about: 'This survey was open from January 10 to January 20, 2026 and captured a community snapshot of digital habits during the winter period. Results are now archived.',
    questionsCount: 3,
    estimatedTime: '7 min',
    activeUntil: 'January 20, 2026',
    author: 'Dana Kol',
    authorAvatar: '',
    participants: 3294,
  },
  {
    id: 'survey:019deda9-096f-7d0c-825e-226ce4c946ff',
    title: 'A Place That Changed You',
    coverImage: '/assets/images/banner/card3.png',
    category: 'society',
    status: StatStatus.Active,
    description: 'We all have places that shaped who we are — a city, a room, a corner of the world. Share yours.',
    about: 'Places leave marks on us — the childhood home, a foreign city, a quiet corner we discovered alone. This survey maps the geography of personal transformation.',
    questionsCount: 3,
    estimatedTime: '5 min',
    activeUntil: 'Anonymous survey',
    author: 'Alex Monroe',
    authorAvatar: '',
    participants: 428,
  },
  {
    id: 'survey:019df434-1423-76e1-9e23-2808d5d51fbf',
    title: 'Survey Universe Community Profile',
    coverImage: '/assets/images/banner/card4.png',
    category: 'society',
    status: StatStatus.Active,
    description: 'Help us understand our community better. Tell us about yourself and the topics you care about most.',
    about: 'This profile survey helps Survey Universe understand who our community members are and what topics matter most to them. Your answers shape how we grow the platform.',
    questionsCount: 12,
    estimatedTime: '15 min',
    activeUntil: 'Anonymous survey',
    author: 'Lena Oris',
    authorAvatar: '',
    participants: 312,
  },
];
