FROM eclipse-temurin:25-jdk AS build
WORKDIR /app

COPY api/api/.mvn ./.mvn
COPY api/api/mvnw api/api/pom.xml ./

RUN chmod +x ./mvnw
RUN ./mvnw dependency:go-offline

COPY api/api/src ./src
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:25-jre
WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
