spring.application.name=api

spring.profiles.active=test


server.servlet.context-path=/api/v1
    
spring.config.jwt.secret=38HcTDqH4AOvDemjrNA5gn0KUaTO03woxJ2t6ZL4JmgWacbwALpY06qnpTgVhScyGMcdWmygmOqsQx0LBRBQnu
spring.config.jwt.token.expiration.access=3600000
spring.config.jwt.token.expiration.refresh=604800000
    
    

