import { SurveyReadSummary } from '../../models/interfaces';

export const SURVEYS_SUMMARY_MOCK: SurveyReadSummary[] = [
  {
    urlId: 'survey:019de9f1-0001-7001-b001-c3d4e5f60101',
    creatorUrlId: 'user:alex-monroe',
    title: 'Do We Rely Too Much on Technology?',
    description: 'Explore how dependent modern society has become on digital tools — and whether that dependence is leading us somewhere we actually want to go.',
    icon: '',
    category: ['society', 'technology', 'digital'],
    estimatedTime: 5,
    publishedAt: '2026-05-14T10:00:00Z',
    surveyType: 'questionnaire',
  },
  {
    urlId: 'survey:019de9f2-0001-7001-b002-c3d4e5f60102',
    creatorUrlId: 'user:lena-oris',
    title: 'Is Space Exploration Worth the Cost?',
    description: 'Humanity spends billions reaching for the stars. Share your perspective on whether that investment makes sense — or where it should go instead.',
    icon: '',
    category: ['science', 'space', 'society'],
    estimatedTime: 4,
    publishedAt: '2026-05-10T14:00:00Z',
    surveyType: 'questionnaire',
  },
  {
    urlId: 'survey:019de9f3-0001-7001-b003-c3d4e5f60103',
    creatorUrlId: 'user:mark-vega',
    title: 'What Shapes Who We Are?',
    description: "Nature, environment, or chance — what do you believe has the greatest influence on a person's identity? No wrong answers.",
    icon: '',
    category: ['psychology', 'philosophy', 'science'],
    estimatedTime: 7,
    publishedAt: '2026-05-06T09:00:00Z',
    surveyType: 'questionnaire',
  },
  {
    urlId: 'survey:019de9f4-0001-7001-b004-c3d4e5f60104',
    creatorUrlId: 'user:sofia-lane',
    title: 'Myths & Facts: The Human Brain',
    description: 'We only use 10% of our brains. Or do we? Separate common misconceptions from science in this quick knowledge test.',
    icon: '',
    category: ['science', 'quiz', 'learning'],
    estimatedTime: 8,
    publishedAt: '2026-04-12T09:30:00Z',
    surveyType: 'test',
  },
  {
    urlId: 'survey:019de95c-3401-7001-a1b2-c3d4e5f60001',
    creatorUrlId: 'user:ivan-petrov',
    title: 'How Do You Handle Stress?',
    description: 'Stress is part of modern life — but how we handle it varies widely. Share your coping strategies and what genuinely works for you.',
    icon: '',
    category: ['psychology', 'wellbeing', 'society'],
    estimatedTime: 5,
    publishedAt: '2026-05-01T08:00:00Z',
    surveyType: 'questionnaire',
  },
  {
    urlId: 'survey:019de96a-0001-7000-8000-c3d4e5f60001',
    creatorUrlId: 'user:dana-kol',
    title: 'How Do You Learn Best?',
    description: 'Everyone absorbs information differently. Help us understand what makes learning click — your preferred formats, timing, and goals.',
    icon: '',
    category: ['psychology', 'education', 'learning'],
    estimatedTime: 10,
    publishedAt: '2026-04-30T12:00:00Z',
    surveyType: 'questionnaire',
  },
  {
    urlId: 'survey:019ded05-5fbc-7e45-919f-ea20c34a34ac',
    creatorUrlId: 'user:alex-monroe',
    title: 'Sleep & Your Daily Energy',
    description: 'Sleep shapes everything — mood, focus, productivity. Tell us about your sleep habits and what you wish you could change.',
    icon: '',
    category: ['psychology', 'science', 'wellbeing'],
    estimatedTime: 7,
    publishedAt: '2026-04-20T10:00:00Z',
    surveyType: 'questionnaire',
  },
  {
    urlId: 'survey:019ded10-b3a3-7bc1-a0bc-7a31ff091616',
    creatorUrlId: 'user:mark-vega',
    title: 'The Human Body: Fact or Fiction?',
    description: 'How well do you know your own body? Test your knowledge of human biology with these quick questions.',
    icon: '',
    category: ['science', 'biology', 'quiz'],
    estimatedTime: 10,
    publishedAt: '2026-04-25T11:00:00Z',
    surveyType: 'test',
  },
  {
    urlId: 'survey:019ded26-cabe-71af-bc58-ac1b804617c0',
    creatorUrlId: 'user:ivan-petrov',
    title: 'Great Thinkers: Know Your Philosophy?',
    description: "From Socrates to Nietzsche — how much do you know about the world's most influential philosophical ideas?",
    icon: '',
    category: ['philosophy', 'history', 'quiz', 'learning', 'society'],
    estimatedTime: 15,
    publishedAt: '2026-05-03T09:00:00Z',
    surveyType: 'test',
  },
  {
    urlId: 'survey:019ded3a-dead-beef-8888-c3d4e5f60001',
    creatorUrlId: 'user:dana-kol',
    title: 'Digital Wellbeing Check — Winter 2026',
    description: "A snapshot of how digital habits affected our community's wellbeing at the start of 2026. Now closed.",
    icon: '',
    category: ['wellbeing', 'technology', 'society'],
    estimatedTime: 7,
    publishedAt: '2026-01-10T08:00:00Z',
    surveyType: 'questionnaire',
  },
  {
    urlId: 'survey:019deda9-096f-7d0c-825e-226ce4c946ff',
    creatorUrlId: 'user:alex-monroe',
    title: 'A Place That Changed You',
    description: 'We all have places that shaped who we are — a city, a room, a corner of the world. Share yours.',
    icon: '',
    category: ['society', 'travel', 'psychology'],
    estimatedTime: 5,
    publishedAt: '2026-05-02T10:00:00Z',
    surveyType: 'questionnaire',
  },
  {
    urlId: 'survey:019df434-1423-76e1-9e23-2808d5d51fbf',
    creatorUrlId: 'user:lena-oris',
    title: 'Survey Universe Community Profile',
    description: 'Help us understand our community better. Tell us about yourself and the topics you care about most.',
    icon: '',
    category: ['society', 'community', 'wellbeing'],
    estimatedTime: 15,
    publishedAt: '2026-05-02T12:00:00Z',
    surveyType: 'questionnaire',
  },
];
