import { SurveyReadSummary } from '../../models/interfaces';

export const SURVEYS_SUMMARY_MOCK: SurveyReadSummary[] = [
  {
    urlId: 'survey-001',
    creatorUrlId: 'creator-alex',
    title: 'Do We Rely Too Much on Technology?',
    description: 'Explore how dependent modern society has become on digital tools — and whether that dependence is leading us somewhere we actually want to go.',
    icon: '',
    category: ['society', 'technology', 'digital'],
    estimatedTime: 5,
    publishedAt: '2026-05-14T10:00:00Z',
    surveyType: 'questionnaire',
  },
  {
    urlId: 'survey-002',
    creatorUrlId: 'creator-lena',
    title: 'Is Space Exploration Worth the Cost?',
    description: 'Humanity spends billions reaching for the stars. Share your perspective on whether that investment makes sense — or where it should go instead.',
    icon: '',
    category: ['science', 'space', 'society'],
    estimatedTime: 4,
    publishedAt: '2026-05-10T14:00:00Z',
    surveyType: 'questionnaire',
  },
  {
    urlId: 'survey-003',
    creatorUrlId: 'creator-mark',
    title: 'What Shapes Who We Are?',
    description: 'Nature, environment, or chance — what do you believe has the greatest influence on a person\'s identity? Ten questions, no wrong answers.',
    icon: '',
    category: ['psychology', 'philosophy', 'science'],
    estimatedTime: 7,
    publishedAt: '2026-05-06T09:00:00Z',
    surveyType: 'questionnaire',
  },
  {
    urlId: 'survey-004',
    creatorUrlId: 'creator-sofia',
    title: 'AI: Tool or Threat?',
    description: 'Artificial intelligence is evolving faster than our regulations. How do you see its role shaping society over the next decade?',
    icon: '',
    category: ['technology', 'philosophy', 'future'],
    estimatedTime: 5,
    publishedAt: '2026-05-01T12:00:00Z',
    surveyType: 'questionnaire',
  },
  {
    urlId: 'survey-005',
    creatorUrlId: 'creator-ivan',
    title: 'Privacy vs Convenience Online',
    description: 'Most people trade personal data for better services every day without thinking about it. Is that a fair deal — or a slow erosion of something important?',
    icon: '',
    category: ['society', 'technology', 'privacy'],
    estimatedTime: 4,
    publishedAt: '2026-04-24T16:00:00Z',
    surveyType: 'questionnaire',
  },
  {
    urlId: 'survey-006',
    creatorUrlId: 'creator-dana',
    title: 'The Psychology of First Impressions',
    description: 'We form judgments in under a second. Test how you make snap decisions — and whether your instincts align with research.',
    icon: '',
    category: ['psychology', 'science', 'behavior'],
    estimatedTime: 6,
    publishedAt: '2026-04-18T11:00:00Z',
    surveyType: 'test',
  },
  {
    urlId: 'survey-007',
    creatorUrlId: 'creator-alex',
    title: 'Myths & Facts: The Human Brain',
    description: 'We only use 10% of our brains. Or do we? Separate common misconceptions from science in this quick knowledge test.',
    icon: '',
    category: ['science', 'quiz', 'learning'],
    estimatedTime: 8,
    publishedAt: '2026-04-12T09:30:00Z',
    surveyType: 'test',
  },
  {
    urlId: 'survey-008',
    creatorUrlId: 'creator-lena',
    title: 'The Future of Work',
    description: 'Remote, hybrid, or in-office — how do you see working life evolving? Your answers help map out where the world is actually heading.',
    icon: '',
    category: ['society', 'future', 'work'],
    estimatedTime: 5,
    publishedAt: '2026-04-05T08:00:00Z',
    surveyType: 'questionnaire',
  },
];
